language: node_js
node_js:
  - "8"
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn install
  - yarn run build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: game/
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
notifications:
  email: false
branches:
  only:
  - master
